#!/usr/bin/env python3

Python 
name = "Sydney"
favorite_color = "Pink"
favorite_activity = "Cooking"
favorite_animal = "Dog"
# Here i assigned all the variables #
print("My name", name)
print("My favorite color:",favorite_color)
print("My favorite activity:", favorite_activity)
print("My favorite animal:", favorite_animal)
# Now python will print the phrase in quotations with the varibale i put as the answer #
